type: "force_control/MyTiagoController"
robot_model_chains: ["gripper_link"]
dt: 0.001

viscous_friction: 0.0
velocity_tolerance: 0.0
static_friction: 0.0

joints:
  torso_lift_joint:
    type: static
  arm_1_joint:
    type: actuated
    motor_torque_constant: 0.136
    reduction_ratio: 100.0
  arm_2_joint:
    type: actuated
    motor_torque_constant: 0.136
    reduction_ratio: 100.0
  arm_3_joint:
    type: actuated
    motor_torque_constant: -0.087
    reduction_ratio: 100.0
  arm_4_joint:
    type: actuated
    motor_torque_constant: -0.087
    reduction_ratio: 100.0
  arm_5_joint:
    type: actuated
    motor_torque_constant: -0.0613
    reduction_ratio: 336.0
  arm_6_joint:
    type: actuated
    motor_torque_constant: 0.0613
    reduction_ratio: 336.0
  arm_7_joint:
    type: actuated
    motor_torque_constant: 0.0613
    reduction_ratio: 336.0

